version: '3.9'
services:
  redis:
    image: redis:6.2.5
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - 'redisdata:/data'
volumes:
  redisdata:
    driver: local